### ISSUE TITLE
exception for domain?

### ISSUE THREAD

**Issue by elinside** [SecurityJosh/DownloadBlocker#1]
Hello
We are planning to use your extension in our organisation.
During our tests we noticed some issues with BMC SmartIT, that the attachments will be blocked also. (with the default config)
Obviously we can add an exception, but only for this application. 
We don't know if there are other applications that will have the same struggles.
I would love to see that we are able to add an exception for our complete domain. like *.mydomain.com instead of adding every myapplication.mydomain.com .

Thanks
Manuel

**Comment by SecurityJosh** [comment]
Hi Manuel,

I've added a new exception type called 'basedomain' which will match on the given value and any subdomains.

Example (will match on example.com, a.example.com, b.example.com etc.):

`exceptions : [
                {
                    "type" : "basedomain",
                    "value" : "example.com"		
                }
            ]`

I've submitted the update (Version 0.0.8) to the Google Chrome Webstore, but it might take a couple of days for it to be approved.

Please let me know if you have any other suggestions or comments :).

If you don't mind sharing, I would be curious about how many users you're rolling this out to as well.

Thanks,

Josh

**Comment by SecurityJosh** [comment]
Hi, just to let you know, the update has now been approved and is live on the Chrome Web Store.
