### ISSUE TITLE
Still able to download even with wild card in place

### ISSUE THREAD

**Issue by jimbo-jones-sys** [SecurityJosh/DownloadBlocker#3]
For example, try to download putty from URL blocks it fine
https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html 

Download from here the windows still pops up and let me download
https://www.microsoft.com/en-gb/microsoft-365/onedrive/download

Config in Regedit
{"rules" : [{"bannedExtensions" : [*],"origin" : "local|server|any","exceptions" : [{"type" : "hostname|basename","value" : "example.com"}]}],"alertConfig" : {"url" : "","headers" : {},"method" : "GET|POST","sendAsJson" : true|false,"postData" : {}}}

![image](https://user-images.githubusercontent.com/62987183/111617339-e3d5ec00-87da-11eb-938c-c77d3629f96e.png)

**Comment by SecurityJosh** [comment]
Hi,

The config you've specified there isn't valid. Are you trying to block any download? If so, this config should do it:

`{"rules":[{"bannedExtensions":["*"],"origin":"any"}]}`

If you let me know what exactly you're trying to block I can give you a hand with the config you need to use.

I'm not sure what's stopping you from downloading Putty but I'm not sure it's the extension in this case.

Thanks,

Josh

**Comment by jimbo-jones-sys** [comment]
Hello josh i have edited it to this yet still no luck I want to block (exe,msi,tar.gz,bat) if possible this is what I currently have enabled

![image](https://user-images.githubusercontent.com/62987183/112340067-1f2f5980-8cb8-11eb-8b87-2cbc8cea68ab.png)

![image](https://user-images.githubusercontent.com/62987183/112340134-30786600-8cb8-11eb-8c15-77b2b1e562b1.png)

**Comment by SecurityJosh** [comment]
Hi,

Please could you do the following:

1) Go to chrome://extensions, find Download Blocker and click the "backround page" link
2) Attempt a download
3) Upload a screenshot of the background page window.

Thanks,

Josh

**Comment by SecurityJosh** [comment]
Hey,

Have you had any luck with this?

Thanks,

Josh

**Comment by SecurityJosh** [comment]
Hi,

Since I haven't heard anything from you, I'm going to close this issue. If it's still a problem please reopen it and provide the requested information.

Thanks,

Josh
