### ISSUE TITLE
Exceptions mode not working?

### ISSUE THREAD

**Issue by bsofd** [SecurityJosh/DownloadBlocker#4]
It seems I cannot get the exception mode to work

The following code blocks all downloads:

{
    "rules" : [
        {
            "bannedExtensions" : ["*"],
            "origin" : "any",
            "action" : "block",
            "titleTemplate" : "Notification Title",
            "messageTemplate" : "Notification message"
        }
    ]
}

However if I try to exclude .msi for instance, all extensions are allowed

{
    "rules" : [
        {
            "bannedExtensions" : ["*"],
            "origin" : "any",
            "exceptions" : [
                {
                    "type" : "fileExtensions",
                    "value" : ["msi"]		
                }
            ],
            "action" : "block",
            "titleTemplate" : "Notification Title",
            "messageTemplate" : "Notification message"
        }
    ]
}

I am hoping its just the lingo?

**Comment by SecurityJosh** [comment]
Hi,

Thanks for reporting this. There was an error which meant that the fileExtensions exception type would result in an exception being thrown by the extension.

I've submitted a version to the Chrome store which should resolve this issue but it needs to be approved before it will be available.

Thanks,

Josh

**Comment by SecurityJosh** [comment]
Hi,

The new version is now live on the Chrome Web store. Please can you confirm this fixes the issue you were seeing?

Thanks,

Josh

**Comment by SecurityJosh** [comment]
Closing this as I'm pretty sure the issue has been resolved.
