### ISSUE TITLE
script is being added to xml file

### ISSUE THREAD

**Issue by InformatiqueOLLN** [SecurityJosh/DownloadBlocker#6]
Hi,
I've got a PHP script who produces an xml : header('Content-Type: text/xml; encoding: utf8;');
The xml produced is correct, in source mode in schrome, but when displayed i get :

<script type="text/javascript"> // https://stackoverflow.com/a/61207836 const ...

![image](https://user-images.githubusercontent.com/19569156/147202181-57beeb7e-088f-49c5-8c5d-dce6264797c9.png)

Could it be possible to not add this on xml file display
Thanks

**Comment by SecurityJosh** [comment]
Hi,

0.1.4 is now live on the Chrome Web store.

Thanks,

Josh
